# Generated by Django 5.1.6 on 2025-03-01 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_alter_product_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_product', models.PositiveIntegerField(verbose_name='Количество товара')),
                ('address', models.TextField()),
                ('tel_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('payment', models.CharField(choices=[('cash', 'Наличными при получении'), ('card', 'Банковской картой')], default='cash', max_length=100, verbose_name='Способ оплаты')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий к заказу')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена заказа')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='shop_app.product', verbose_name='Продукт для заказа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
