# Generated by Django 5.1.6 on 2025-03-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Your order in the queue', 'Ваш заказ в очереди'), ('On the way to you', 'Заказ уже на пути к вам'), ('The courier has arrived and is ready to place the order', 'Курьер приехал, готов отдать заказ')], default='Your order in the queue', max_length=150, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
