# Generated by Django 5.1.6 on 2025-03-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0006_order_status_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Your order in the queue', 'Ваш заказ в очереди'), ('On the way to you', 'Заказ уже на пути к вам'), ('The courier has arrived and is ready to place the order', 'Курьер приехал, готов отдать заказ')], default='Ваш заказ в очереди', max_length=150, verbose_name='Статус заказа'),
        ),
    ]
