# Generated by Django 5.1.6 on 2025-03-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tel_number',
            field=models.CharField(default=375291748581, max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('queue', 'Ваш заказ в очереди'), ('on_the_way', 'Заказ уже на пути к вам'), ('arrived', 'Курьер приехал, готов отдать заказ')], default='Your order in the queue', max_length=150, verbose_name='Статус заказа'),
        ),
    ]
