# Generated by Django 5.1.6 on 2025-03-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('queue', 'Ваш заказ в очереди'), ('on_the_way', 'Заказ уже на пути к вам'), ('arrived', 'Курьер приехал, готов отдать заказ')], default='queue', max_length=150, verbose_name='Статус заказа'),
        ),
    ]
